// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpneDJlz78nTTMEmGsLCqoU0S0M1vd6GM',
    appId: '1:193241607977:android:91eef7ba933d27a0045138',
    messagingSenderId: '193241607977',
    projectId: 'online-coffee-shop-b67e3',
    databaseURL: 'https://online-coffee-shop-b67e3-default-rtdb.firebaseio.com',
    storageBucket: 'online-coffee-shop-b67e3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBrGfU9bjax8b27tI5P7oEFRkLfZBbGmHk',
    appId: '1:193241607977:ios:6a1e21a163fde789045138',
    messagingSenderId: '193241607977',
    projectId: 'online-coffee-shop-b67e3',
    databaseURL: 'https://online-coffee-shop-b67e3-default-rtdb.firebaseio.com',
    storageBucket: 'online-coffee-shop-b67e3.appspot.com',
    iosBundleId: 'com.example.craftyBay',
  );
}
